character(goku, saiyan, male, 9000, fast, spirit_bomb, super_saiyan).
character(vegeta, saiyan, male, 8500, fast, final_flash, super_saiyan).
character(piccolo, namekian, male, 8000, fast, hellzone_grenade, fuse_with_kami).
character(gohan, halfsaiyan, male, 7500, fast, fatherson_kamehameha, super_saiyan_2).
character(future_trunks, halfsaiyan, male, 7800, fast, heat_dome_attack, super_saiyan).
character(krillin, human, male, 2000, average, solar_flare, none).
character(tien, human, male, 2200, fast, four_witches_technique, none).
character(yamcha, human, male, 1800, average, wolf_fang_fist, none).
character(chiaotzu, human, male, 1400, slow, psychic_powers, none).
character(bulma, human, female, 5, none, none, none).
character(master_roshi, human, male, 1500, slow, max_power_kamehameha, none).
character(android_18, android, female, 8000, fast, infinity_bullet, none).
character(android_17, android, male, 7800, fast, nonstop_violence, none).
character(cell, bioandroid, male, 10000, fast, solar_kamehameha, perfect_form).
character(frieza, frost_demon, male, 12000, fast, supernova, final_form).
character(majin_buu, majin, male, 15000, slow, chocolate_beam, various_forms).
character(yamu, human, male, 1000, slow, none, none).
character(spopovich, human, male, 1100, average, none, majin_form).
character(videl, human, female, 300, average, none, none).
character(dabura, demon, male, 6500, fast, stone_spit, majin_form).
character(hercule, human, male, 30, slow, none, none).
character(oxking, human, male, 700, slow, fireball, none).
character(chichi, human, female, 130, slow, none, none).
character(puar, shapeshifter, male, 5, slow, none, none).
character(oolong, shapeshifter, male, 10, slow, none, none).
character(launch, human, female, 5, fast, none, none).
character(mr_popo, genie, male, 1000, slow, none, none).
character(kami, namekian, male, 3000, slow, none, merge_with_piccolo).
character(king_kai, kai, male, 5000, slow, none, none).
character(bubbles, monkey, male, 100, slow, none, none).
character(gregory, grasshopper, male, 5, slow, none, none).
character(dende, namekian, male, 2000, slow, none, none).
character(nail, namekian, male, 42000, slow, none, merge_with_piccolo).
character(great_saiyaman, saiyan, male, 4500, fast, saiyan_man_pose, none).
character(videl, human, female, 300, average, none, none).
character(raditz, saiyan, male, 1500, fast, saturday_crush, none).
character(nappa, saiyan, male, 4000, average, break_cannon, none).
character(zarbon, alien, male, 20000, fast, monster_crush, transformation).
character(dodoria, alien, male, 20000, fast, dodoria_launcher, transformation).
character(captain_ginyu, alien, male, 120000, fast, body_change, transformation).
character(burter, alien, male, 40000, fast, blue_cannonball, transformation).
character(recoome, alien, male, 40000, fast, recoome_ultra_fighting_bomber, transformation).
character(guldo, alien, male, 40000, slow, guldo_freeze, transformation).
character(cell_jr, bioandroid, male, 4000, fast, none, none).
character(android_16, android, male, 10000, slow, hells_impact, none).
character(android_19, android, male, 10000, slow, none, none).
character(android_20, android, male, 10000, slow, none, none).
character(babidi, wizard, male, 2000, slow, none, none).
character(yakon, demon, male, 8000, fast, none, absorption).
character(pui_pui, alien, male, 4000, fast, none, transformation).
character(android_13, android, male, 8000, fast, none, none).
character(bojack, alien, male, 40000, fast, galactic_blow, transformation).
character(janemba, demon, male, 20000, fast, dimension_sword, transformation).
character(broly, saiyan, male, 100000, fast, omega_blaster, super_saiyan).
character(cooler, frost_demon, male, 50000, fast, darkness_eye_beam, transformation).
character(android_14, android, male, 8000, fast, none, none).
character(android_15, android, male, 8000, fast, none, none).
character(majin_vegeta, saiyan, male, 9000, fast, final_impact, majin_form).
character(dr_gero, android, male, 4000, slow, none, none).
character(android_8, android, male, 3000, slow, none, none).
character(mercenary_tao, human, male, 1800, average, dodon_ray, none).
character(nam, human, male, 50, slow, none, none).
character(king_piccolo, demon, male, 2600, fast, mouth_energy_wave, none).
character(launch, human, female, 5, fast, none, none).
character(emperor_pilaf, human, male, 10, slow, none, none).
character(upa, human, male, 10, slow, none, none).
character(mai, human, female, 10, slow, none, none).
character(mr_satan, human, male, 50, slow, none, none).
character(vados, angel, female, 200000, fast, none, none).
character(whis, angel, male, 200000, fast, temporal_doover, none).
